### ISSUE TITLE
Images Missing

### ISSUE THREAD

**Issue by aishangcengloua** [iurteaga/menstrual_cycle_analysis#3]
Hello,

After reading your paper titled "A predictive model for next cycle start date that accounts for adherence in menstrual self-tracking," I gained valuable insights. However, I noticed that some images are missing in the appendix section. Would it be possible for you to provide the missing appendix images?

 I would greatly appreciate it.
![image](https://github.com/iurteaga/menstrual_cycle_analysis/assets/79522879/e2711779-fecc-459c-b75d-f6c7ff40a39b)

**Comment by iurteaga** [comment]
Dear @aishangcengloua,

Thanks for noticing this issue.

Please refer to the SI information provided in the doc/prediction directory for its complete version:

[doc/prediction/jamia_si_2021.pdf](https://github.com/iurteaga/menstrual_cycle_analysis/blob/master/doc/prediction/jamia_si_2021.pdf)

I hope you find it useful, and thanks again.
